[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[dev]
  framework = "#custom"
  command = "node server.js"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200